/**
 * CreatePlaybook handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createPlaybook } from "@paritya/api-server/domains/playbooks/handlers";
import type { PlaybooksDDDDependencies } from "@paritya/api-server/domains/playbooks";
import { createPlaybook as createPlaybookEntity } from "@paritya/factories/playbooks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { PLAYBOOKS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreatePlaybook", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PlaybooksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PlaybooksDDDDependencies>(
      PLAYBOOKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createPlaybookEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreatePlaybook, "execute").mockResolvedValue(useCaseResult);

    await createPlaybook(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreatePlaybook.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
