/**
 * GetPlaybook handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPlaybook } from "@paritya/api-server/domains/playbooks/handlers";
import type { PlaybooksDDDDependencies } from "@paritya/api-server/domains/playbooks";
import { createPlaybook as createPlaybookEntity } from "@paritya/factories/playbooks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { PLAYBOOKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPlaybook", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PlaybooksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PlaybooksDDDDependencies>(
      PLAYBOOKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPlaybookEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPlaybook, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { playbookId: entity.id };

    await getPlaybook(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPlaybook.execute).toHaveBeenCalledWith(expect.objectContaining({ playbookId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { playbookId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPlaybook, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPlaybook(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
