/**
 * Case Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CaseEntity } from "@paritya/core/cases/models/index.js";
import { casesSchemas } from "@paritya/core/cases";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cas";

export function createCase(overrides: Partial<CaseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cas_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    status: overrides.status ?? "open",
    type: overrides.type ?? "fairness_breach",
    useCaseId: overrides.useCaseId ?? faker.string.uuid(),
    ...overrides,
  };

  return casesSchemas.Case.parse(raw);
}

export function caseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCase(overrides));
}
