/**
 * EvidencePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePack DTOs
 *
 * DDD: Application DTOs for EvidencePack use cases.
 */

import type { CreateEvidencePackRequestInput, GetEvidencePackParams, ListEvidencePacksParams } from "@paritya/core/evidence/types";

export type ListEvidencePacksInput = ListEvidencePacksParams;

export type CreateEvidencePackInput = CreateEvidencePackRequestInput;

export type GetEvidencePackInput = GetEvidencePackParams;

export type ListEvidencePacksOutput = {};

export type CreateEvidencePackOutput = {};

export type GetEvidencePackOutput = {};
