/**
 * ExecuteListPlaybooks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPlaybooks Use Case
 *
 * DDD: Application use case for list Playbook.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPlaybooksInput, ListPlaybooksOutput } from "../dto/playbook.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { PlaybookRepository } from "../ports";

export class ExecuteListPlaybooks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly playbook: PlaybookRepository
  ) {}

  async execute(input: ListPlaybooksInput): Promise<ListPlaybooksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.plbId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.playbook.listPlaybooks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPlaybooksOutput;
  }
}
