/**
 * ExecuteCreatePlaybook - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePlaybook Use Case
 *
 * DDD: Application use case for create Playbook.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePlaybookInput, CreatePlaybookOutput } from "../dto/playbook.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { PlaybookRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePlaybook {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly playbook: PlaybookRepository
  ) {}

  async execute(input: CreatePlaybookInput): Promise<CreatePlaybookOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.plbId();

    // All field names extracted from OpenAPI spec: bodyMarkdown, regionHints, summary, title, useCaseType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.useCaseType) {
      throw new ValidationError("useCaseType is required");
    }
    if (!input.title) {
      throw new ValidationError("title is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (playbooks domain)
    const entityId = this.idGenerator.plbId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.playbook.createPlaybook({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePlaybookOutput;
  }
}
