/**
 * BreachRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BreachRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BreachRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BreachRepository,
} from "@paritya/services/monitoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BreachRepositoryDdb } from "./breach-repository.ddb.js";

/**
 * BreachRepositoryAdapter
 *
 * Implements BreachRepository port for infrastructure layer.
 */
export class BreachRepositoryAdapter implements BreachRepository {
  private readonly ddb: BreachRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BreachRepositoryDdb(this.dynamoClient);
  }

  async listFairnessBreaches(input: Parameters<BreachRepository['listFairnessBreaches']>[0]): Promise<Awaited<ReturnType<BreachRepository['listFairnessBreaches']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFairnessBreaches(input);
  }

  async createFairnessBreach(input: Parameters<BreachRepository['createFairnessBreach']>[0]): Promise<Awaited<ReturnType<BreachRepository['createFairnessBreach']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFairnessBreach(input);
  }
}
