/**
 * ListBreach DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFairnessBreachesParams } from "@paritya/core/monitoring";

export function createListBreachRequest(overrides: Partial<ListFairnessBreachesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
