/**
 * CreateEvidencePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createEvidencePack } from "@paritya/api-server/domains/evidence/handlers";
import type { EvidenceDDDDependencies } from "@paritya/api-server/domains/evidence";
import { createEvidencePack as createEvidencePackEntity } from "@paritya/factories/evidence";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { EVIDENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateEvidencePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidenceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidenceDDDDependencies>(
      EVIDENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createEvidencePackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateEvidencePack, "execute").mockResolvedValue(useCaseResult);

    await createEvidencePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateEvidencePack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
