/**
 * Case DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Case DTOs
 *
 * DDD: Application DTOs for Case use cases.
 */

import type { CreateCaseRequestInput, GetCaseParams, ListCasesParams, UpdateCaseParams, UpdateCaseRequestInput } from "@paritya/core/cases/types";

export type ListCasesInput = ListCasesParams;

export type CreateCaseInput = CreateCaseRequestInput;

export type GetCaseInput = GetCaseParams;

export type UpdateCaseInput = UpdateCaseParams & UpdateCaseRequestInput;

export type ListCasesOutput = {};

export type CreateCaseOutput = {};

export type GetCaseOutput = {};

export type UpdateCaseOutput = {};
