/**
 * Repository interface for Playbook
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PlaybookEntity
} from "../models/playbook.entity.js";
import type {
  ListPlaybooksParams,
  Playbook
} from "../types/index.js";
/**
 * PlaybookRepository Interface
 */
export interface PlaybookRepository extends CreateReadRepository<PlaybookEntity, Playbook, string, ListPlaybooksParams> {

}
