/**
 * ExecuteListDossiers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDossiers Use Case
 *
 * DDD: Application use case for list Dossier.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDossiersInput, ListDossiersOutput } from "../dto/dossier.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { DossierRepository } from "../ports";

export class ExecuteListDossiers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dossier: DossierRepository
  ) {}

  async execute(input: ListDossiersInput): Promise<ListDossiersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dosId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dossier.listDossiers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDossiersOutput;
  }
}
