/**
 * ExecuteGetDossier - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDossier Use Case
 *
 * DDD: Application use case for get Dossier.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDossierInput, GetDossierOutput } from "../dto/dossier.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { DossierRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDossier {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dossier: DossierRepository
  ) {}

  async execute(input: GetDossierInput): Promise<GetDossierOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dosId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dossierId) {
      throw new ValidationError("dossierId is required");
    }
    const dossierId = (input as any).dossierId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dossier.getDossier({ dossierId: dossierId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${dossierId}`);
    }

    return entity as GetDossierOutput;
  }
}
