/**
 * UpdateCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateCase } from "@paritya/api-server/domains/cases/handlers";
import type { CasesDDDDependencies } from "@paritya/api-server/domains/cases";
import { createCase as createCaseEntity } from "@paritya/factories/cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { CASES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CasesDDDDependencies>(
      CASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createCaseEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { caseId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateCase, "execute").mockResolvedValue(useCaseResult);

    await updateCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateCase.execute).toHaveBeenCalledWith(expect.objectContaining({ caseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
