/**
 * Playbook DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Playbook DTOs
 *
 * DDD: Application DTOs for Playbook use cases.
 */

import type { CreatePlaybookRequestInput, GetPlaybookParams, ListPlaybooksParams } from "@paritya/core/playbooks/types";

export type ListPlaybooksInput = ListPlaybooksParams;

export type CreatePlaybookInput = CreatePlaybookRequestInput;

export type GetPlaybookInput = GetPlaybookParams;

export type ListPlaybooksOutput = {};

export type CreatePlaybookOutput = {};

export type GetPlaybookOutput = {};
