/**
 * Repository interface for Case
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CaseEntity
} from "../models/case.entity.js";
import type {
  ListCasesParams,
  Case,
  UpdateCaseRequestInput
} from "../types/index.js";
/**
 * CaseRepository Interface
 */
export interface CaseRepository extends CreateUpdateReadRepository<CaseEntity, Case, UpdateCaseRequestInput, string, ListCasesParams> {

}
