/**
 * Dossier DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dossier DTOs
 *
 * DDD: Application DTOs for Dossier use cases.
 */

import type { CreateDossierRequestInput, GetDossierParams, ListDossiersParams, SubmitDossierParams } from "@paritya/core/dossiers/types";

export type ListDossiersInput = ListDossiersParams;

export type CreateDossierInput = CreateDossierRequestInput;

export type GetDossierInput = GetDossierParams;

export type SubmitDossierInput = SubmitDossierParams;

export type ListDossiersOutput = {};

export type CreateDossierOutput = {};

export type GetDossierOutput = {};

export type SubmitDossierOutput = {};
