/**
 * LanguageTest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LanguageTest DTOs
 *
 * DDD: Application DTOs for LanguageTest use cases.
 */

import type { CreateLanguageTestParams, CreateLanguageTestRequestInput } from "@paritya/core/dossiers/types";

export type CreateLanguageTestInput = CreateLanguageTestParams & CreateLanguageTestRequestInput;

export type CreateLanguageTestOutput = {};
