/**
 * Monitoring DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Monitoring Domain Module - Composition root
 *
 * DDD: Composition root for monitoring domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BreachRepositoryAdapter,
  MetricRepositoryAdapter,
} from "@paritya/adapters/monitoring";
import { getIdGeneratorService } from "@paritya/adapters";
import type { AdapterDynamoDBClient } from "@paritya/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateFairnessBreach,
  ExecuteListFairnessBreaches,
  ExecuteListMonitoringMetrics,
  ExecuteSubmitMonitoringMetric,
} from "@paritya/services/monitoring/usecases";
// Ports (interfaces)
import type {
  BreachRepository,
  MetricRepository,
} from "@paritya/services/monitoring/ports";

export interface MonitoringDomainModule {
  repos: {
    breaches: BreachRepository;
    metrics: MetricRepository;
  };
  useCases: {
    breaches: {
      create: ExecuteCreateFairnessBreach;
      list: ExecuteListFairnessBreaches;
    };
    metrics: {
      create: ExecuteSubmitMonitoringMetric;
      list: ExecuteListMonitoringMetrics;
    };
  };
}

export function buildMonitoringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MonitoringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      breaches?: BreachRepository;
      metrics?: MetricRepository;
    } = {};

    obj.breaches = new BreachRepositoryAdapter(dynamoClient);
    obj.metrics = new MetricRepositoryAdapter(dynamoClient);
    return {
      breaches: obj.breaches!,
      metrics: obj.metrics!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    breaches: {
      create: new ExecuteCreateFairnessBreach(executionContext, idGenerator, repos.breaches),
      list: new ExecuteListFairnessBreaches(executionContext, idGenerator, repos.breaches),
    },
    metrics: {
      create: new ExecuteSubmitMonitoringMetric(executionContext, idGenerator, repos.metrics),
      list: new ExecuteListMonitoringMetrics(executionContext, idGenerator, repos.metrics),
    },
  };
  return { repos, useCases: useCases as MonitoringDomainModule["useCases"] };
}
