/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as appealsRoutes from "../../domains/appeals/routes/index.js";
import * as casesRoutes from "../../domains/cases/routes/index.js";
import * as dossiersRoutes from "../../domains/dossiers/routes/index.js";
import * as evidenceRoutes from "../../domains/evidence/routes/index.js";
import * as gatesRoutes from "../../domains/gates/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as monitoringRoutes from "../../domains/monitoring/routes/index.js";
import * as playbooksRoutes from "../../domains/playbooks/routes/index.js";
import * as usecasesRoutes from "../../domains/usecases/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "appeals", mod: appealsRoutes },
  { domain: "cases", mod: casesRoutes },
  { domain: "dossiers", mod: dossiersRoutes },
  { domain: "evidence", mod: evidenceRoutes },
  { domain: "gates", mod: gatesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "monitoring", mod: monitoringRoutes },
  { domain: "playbooks", mod: playbooksRoutes },
  { domain: "usecases", mod: usecasesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
