/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@paritya/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "appeals", "cases", "dossiers", "evidence", "gates", "identity", "monitoring", "playbooks", "usecases"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      appeals: [{ method: "GET", path: "/v1/appeals" }, { method: "POST", path: "/v1/appeals" }, { method: "GET", path: "/v1/appeals/:appealPathId" }, { method: "PATCH", path: "/v1/appeals/:appealPathId" }],
      cases: [{ method: "GET", path: "/v1/cases" }, { method: "POST", path: "/v1/cases" }, { method: "GET", path: "/v1/cases/:caseId" }, { method: "PATCH", path: "/v1/cases/:caseId" }],
      dossiers: [{ method: "GET", path: "/v1/dossiers" }, { method: "POST", path: "/v1/dossiers" }, { method: "GET", path: "/v1/dossiers/:dossierId" }, { method: "POST", path: "/v1/dossiers/:dossierId" }, { method: "POST", path: "/v1/dossiers/:dossierId/checklist-items" }, { method: "POST", path: "/v1/dossiers/:dossierId/language-tests" }],
      evidence: [{ method: "GET", path: "/v1/evidence-packs" }, { method: "POST", path: "/v1/evidence-packs" }, { method: "GET", path: "/v1/evidence-packs/:evidencePackId" }],
      gates: [{ method: "GET", path: "/v1/use-cases/:useCaseId/gates" }, { method: "POST", path: "/v1/use-cases/:useCaseId/gates" }, { method: "GET", path: "/v1/sandboxes" }, { method: "GET", path: "/v1/sandboxes/:sandboxPermitId" }, { method: "POST", path: "/v1/sandboxes/:sandboxPermitId/extend" }, { method: "POST", path: "/v1/sandboxes/:sandboxPermitId/revoke" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      monitoring: [{ method: "GET", path: "/v1/monitoring/metrics" }, { method: "POST", path: "/v1/monitoring/metrics" }, { method: "GET", path: "/v1/monitoring/breaches" }, { method: "POST", path: "/v1/monitoring/breaches" }],
      playbooks: [{ method: "GET", path: "/v1/playbooks" }, { method: "POST", path: "/v1/playbooks" }, { method: "GET", path: "/v1/playbooks/:playbookId" }],
      usecases: [{ method: "GET", path: "/v1/use-cases" }, { method: "POST", path: "/v1/use-cases" }, { method: "GET", path: "/v1/use-cases/:useCaseId" }, { method: "PATCH", path: "/v1/use-cases/:useCaseId" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
