/**
 * EvidencePack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EvidencePackEntity } from "@paritya/core/evidence/models/index.js";
import { evidenceSchemas } from "@paritya/core/evidence";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "evd";

export function createEvidencePack(overrides: Partial<EvidencePackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ep_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    includesRawPii: overrides.includesRawPii ?? faker.datatype.boolean(),
    status: overrides.status ?? "pending",
    useCaseId: overrides.useCaseId ?? faker.string.uuid(),
    ...overrides,
  };

  return evidenceSchemas.EvidencePack.parse(raw);
}

export function evidencePackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEvidencePack(overrides));
}
