/**
 * Cases DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cases Domain Module - Composition root
 *
 * DDD: Composition root for cases domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CaseRepositoryAdapter,
} from "@paritya/adapters/cases";
import { getIdGeneratorService } from "@paritya/adapters";
import type { AdapterDynamoDBClient } from "@paritya/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCase,
  ExecuteGetCase,
  ExecuteListCases,
  ExecuteUpdateCase,
} from "@paritya/services/cases/usecases";
// Ports (interfaces)
import type {
  CaseRepository,
} from "@paritya/services/cases/ports";

export interface CasesDomainModule {
  repos: {
    cases: CaseRepository;
  };
  useCases: {
    cases: {
      create: ExecuteCreateCase;
      get: ExecuteGetCase;
      list: ExecuteListCases;
      update: ExecuteUpdateCase;
    };
  };
}

export function buildCasesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CasesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      cases?: CaseRepository;
    } = {};

    obj.cases = new CaseRepositoryAdapter(dynamoClient);
    return {
      cases: obj.cases!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    cases: {
      create: new ExecuteCreateCase(executionContext, idGenerator, repos.cases),
      get: new ExecuteGetCase(executionContext, idGenerator, repos.cases),
      list: new ExecuteListCases(executionContext, idGenerator, repos.cases),
      update: new ExecuteUpdateCase(executionContext, idGenerator, repos.cases),
    },
  };
  return { repos, useCases: useCases as CasesDomainModule["useCases"] };
}
