/**
 * CaseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseRepository Port
 *
 * DDD: Application port for caserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCaseInput, CreateCaseOutput, GetCaseInput, GetCaseOutput, ListCasesInput, ListCasesOutput, UpdateCaseInput, UpdateCaseOutput } from "../dto/case.dto";
export interface CaseRepository {
  listCases(input: ListCasesInput): Promise<ListCasesOutput>;
  createCase(input: CreateCaseInput): Promise<CreateCaseOutput>;
  getCase(input: GetCaseInput): Promise<GetCaseOutput>;
  updateCase(input: UpdateCaseInput): Promise<UpdateCaseOutput>;
}

export type { CreateCaseInput, CreateCaseOutput, GetCaseInput, GetCaseOutput, ListCasesInput, ListCasesOutput, UpdateCaseInput, UpdateCaseOutput } from "../dto/case.dto";
