/**
 * ChecklistItemRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChecklistItemRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ChecklistItemRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ChecklistItemRepository,
} from "@paritya/services/dossiers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ChecklistItemRepositoryDdb } from "./checklist-item-repository.ddb.js";

/**
 * ChecklistItemRepositoryAdapter
 *
 * Implements ChecklistItemRepository port for infrastructure layer.
 */
export class ChecklistItemRepositoryAdapter implements ChecklistItemRepository {
  private readonly ddb: ChecklistItemRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ChecklistItemRepositoryDdb(this.dynamoClient);
  }

  async upsertChecklistItem(input: Parameters<ChecklistItemRepository['upsertChecklistItem']>[0]): Promise<Awaited<ReturnType<ChecklistItemRepository['upsertChecklistItem']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertChecklistItem(input);
  }
}
