/**
 * DossierRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DossierRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DossierRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DossierRepository,
} from "@paritya/services/dossiers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DossierRepositoryDdb } from "./dossier-repository.ddb.js";

/**
 * DossierRepositoryAdapter
 *
 * Implements DossierRepository port for infrastructure layer.
 */
export class DossierRepositoryAdapter implements DossierRepository {
  private readonly ddb: DossierRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DossierRepositoryDdb(this.dynamoClient);
  }

  async listDossiers(input: Parameters<DossierRepository['listDossiers']>[0]): Promise<Awaited<ReturnType<DossierRepository['listDossiers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDossiers(input);
  }

  async createDossier(input: Parameters<DossierRepository['createDossier']>[0]): Promise<Awaited<ReturnType<DossierRepository['createDossier']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDossier(input);
  }

  async getDossier(input: Parameters<DossierRepository['getDossier']>[0]): Promise<Awaited<ReturnType<DossierRepository['getDossier']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDossier(input);
  }

  async submitDossier(input: Parameters<DossierRepository['submitDossier']>[0]): Promise<Awaited<ReturnType<DossierRepository['submitDossier']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitDossier(input);
  }
}
