/**
 * LanguageTestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LanguageTestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LanguageTestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LanguageTestRepository,
} from "@paritya/services/dossiers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LanguageTestRepositoryDdb } from "./language-test-repository.ddb.js";

/**
 * LanguageTestRepositoryAdapter
 *
 * Implements LanguageTestRepository port for infrastructure layer.
 */
export class LanguageTestRepositoryAdapter implements LanguageTestRepository {
  private readonly ddb: LanguageTestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LanguageTestRepositoryDdb(this.dynamoClient);
  }

  async createLanguageTest(input: Parameters<LanguageTestRepository['createLanguageTest']>[0]): Promise<Awaited<ReturnType<LanguageTestRepository['createLanguageTest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createLanguageTest(input);
  }
}
