/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @paritya/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@paritya/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@paritya/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@paritya/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@paritya/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@paritya/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _appeals from "./appeals/index.js";
import * as _cases from "./cases/index.js";
import * as _dossiers from "./dossiers/index.js";
import * as _evidence from "./evidence/index.js";
import * as _gates from "./gates/index.js";
import * as _identity from "./identity/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _playbooks from "./playbooks/index.js";
import * as _usecases from "./usecases/index.js";

// Export as namespaces
export const _shared = __shared;
export const appeals = _appeals;
export const cases = _cases;
export const dossiers = _dossiers;
export const evidence = _evidence;
export const gates = _gates;
export const identity = _identity;
export const monitoring = _monitoring;
export const playbooks = _playbooks;
export const usecases = _usecases;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@paritya/core"; activity.types.*
//   - Direct exports: import * from "@paritya/core/activity/types/index.js"
//   - Direct exports: import * from "@paritya/core/activity/repositories/index.js"
//   - Direct exports: import * from "@paritya/core/activity/models/index.js"
//   - Direct exports: import * from "@paritya/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Appeals Service
export { schemas as AppealsSchemas } from "./appeals/schemas/appeals.schemas.js";

// Cases Service
export { schemas as CasesSchemas } from "./cases/schemas/cases.schemas.js";

// Dossiers Service
export { schemas as DossiersSchemas } from "./dossiers/schemas/dossiers.schemas.js";

// Evidence Service
export { schemas as EvidenceSchemas } from "./evidence/schemas/evidence.schemas.js";

// Gates Service
export { schemas as GatesSchemas } from "./gates/schemas/gates.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Monitoring Service
export { schemas as MonitoringSchemas } from "./monitoring/schemas/monitoring.schemas.js";

// Playbooks Service
export { schemas as PlaybooksSchemas } from "./playbooks/schemas/playbooks.schemas.js";

// Usecases Service
export { schemas as UsecasesSchemas } from "./usecases/schemas/usecases.schemas.js";

