/**
 * BreachRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BreachRepository Port
 *
 * DDD: Application port for breachrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateFairnessBreachInput, CreateFairnessBreachOutput, ListFairnessBreachesInput, ListFairnessBreachesOutput } from "../dto/breach.dto";
export interface BreachRepository {
  listFairnessBreaches(input: ListFairnessBreachesInput): Promise<ListFairnessBreachesOutput>;
  createFairnessBreach(input: CreateFairnessBreachInput): Promise<CreateFairnessBreachOutput>;
}

export type { CreateFairnessBreachInput, CreateFairnessBreachOutput, ListFairnessBreachesInput, ListFairnessBreachesOutput } from "../dto/breach.dto";
