/**
 * Handlers for LanguageTest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DossiersDomainModule } from "../dependencies/dossiers-ddd.dependencies.js";
import type { CreateLanguageTestInput } from "@paritya/services/dossiers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/dossiers/{dossierId}/language-tests
 * Operation: createLanguageTest
 */
export async function createLanguageTest(
  request: FastifyRequest<{ Params: { dossierId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DossiersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateLanguageTestInput = {
    dossierId: request.params.dossierId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.languageTests.create.execute(input);
  return reply.code(201).send(result);
}


