/**
 * GetCase DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCaseParams } from "@paritya/core/cases";

export function createGetCaseRequest(overrides: Partial<GetCaseParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
