/**
 * ExecuteCreateEvidencePack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateEvidencePack Use Case
 *
 * DDD: Application use case for create EvidencePack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateEvidencePackInput, CreateEvidencePackOutput } from "../dto/evidence-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { EvidencePackRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateEvidencePack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidencePack: EvidencePackRepository
  ) {}

  async execute(input: CreateEvidencePackInput): Promise<CreateEvidencePackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: includeCivilSocietySummary, includesRawPii, rawPiiAuditReason, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.useCaseId) {
      throw new ValidationError("useCaseId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (evidence domain)
    const entityId = this.idGenerator.evdId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.evidencePack.createEvidencePack({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateEvidencePackOutput;
  }
}
