/**
 * Playbook Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/playbooks.openapi.types.js";
import { schemas } from "../schemas/playbooks.schemas.js";

/**
 * Entity: PlaybookEntity
 * Description: Represents the Playbook domain model.
 * Source: schemas.Playbook
 * Type: Domain Entity (API)
 */
export const PlaybookEntitySchema = schemas.Playbook;
export type PlaybookEntity = components["schemas"]["Playbook"];
