/**
 * CreateUseCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createUseCase } from "@paritya/api-server/domains/usecases/handlers";
import type { UsecasesDDDDependencies } from "@paritya/api-server/domains/usecases";
import { createUseCase as createUseCaseEntity } from "@paritya/factories/usecases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { USECASES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateUseCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: UsecasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<UsecasesDDDDependencies>(
      USECASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createUseCaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateUseCase, "execute").mockResolvedValue(useCaseResult);

    await createUseCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateUseCase.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
