/**
 * UpdateUseCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateUseCase } from "@paritya/api-server/domains/usecases/handlers";
import type { UsecasesDDDDependencies } from "@paritya/api-server/domains/usecases";
import { createUseCase as createUseCaseEntity } from "@paritya/factories/usecases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { USECASES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateUseCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: UsecasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<UsecasesDDDDependencies>(
      USECASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createUseCaseEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { useCaseId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateUseCase, "execute").mockResolvedValue(useCaseResult);

    await updateUseCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateUseCase.execute).toHaveBeenCalledWith(expect.objectContaining({ useCaseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
