/**
 * ExecuteCreateFairnessBreach - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateFairnessBreach Use Case
 *
 * DDD: Application use case for create Breach.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateFairnessBreachInput, CreateFairnessBreachOutput } from "../dto/breach.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { BreachRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateFairnessBreach {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breach: BreachRepository
  ) {}

  async execute(input: CreateFairnessBreachInput): Promise<CreateFairnessBreachOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: metricId, summary, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.metricId) {
      throw new ValidationError("metricId is required");
    }
    if (!input.useCaseId) {
      throw new ValidationError("useCaseId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (monitoring domain)
    const entityId = this.idGenerator.monId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.breach.createFairnessBreach({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateFairnessBreachOutput;
  }
}
