/**
 * ExecuteListMonitoringMetrics - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMonitoringMetrics Use Case
 *
 * DDD: Application use case for list Metric.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMonitoringMetricsInput, ListMonitoringMetricsOutput } from "../dto/metric.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { MetricRepository } from "../ports";

export class ExecuteListMonitoringMetrics {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly metric: MetricRepository
  ) {}

  async execute(input: ListMonitoringMetricsInput): Promise<ListMonitoringMetricsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.metric.listMonitoringMetrics({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMonitoringMetricsOutput;
  }
}
