/**
 * CreateRevoke DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RevokeSandboxPermitParams } from "@paritya/core/gates";

export function createCreateRevokeRequest(overrides: Partial<RevokeSandboxPermitParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
