/**
 * Handlers for Metric
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MonitoringDomainModule } from "../dependencies/monitoring-ddd.dependencies.js";
import type { ListMonitoringMetricsInput, SubmitMonitoringMetricInput } from "@paritya/services/monitoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/monitoring/metrics
 * Operation: listMonitoringMetrics
 */
export async function listMonitoringMetrics(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], useCaseId?: string | string[], thresholdBreached?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MonitoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListMonitoringMetricsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.metrics.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/monitoring/metrics
 * Operation: submitMonitoringMetric
 */
export async function submitMonitoringMetric(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: MonitoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitMonitoringMetricInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.metrics.create.execute(input);
  return reply.code(201).send(result);
}


