/**
 * Handlers for Appeal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AppealsDomainModule } from "../dependencies/appeals-ddd.dependencies.js";
import type { CreateAppealPathInput, GetAppealPathInput, ListAppealPathsInput, UpdateAppealPathInput } from "@paritya/services/appeals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/appeals
 * Operation: listAppealPaths
 */
export async function listAppealPaths(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], useCaseId?: string | string[], modelVersion?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AppealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAppealPathsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.appeals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/appeals
 * Operation: createAppealPath
 */
export async function createAppealPath(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AppealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAppealPathInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.appeals.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/appeals/{appealPathId}
 * Operation: getAppealPath
 */
export async function getAppealPath(
  request: FastifyRequest<{ Params: { appealPathId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AppealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAppealPathInput = {
    appealPathId: request.params.appealPathId,
  };
  const result = await deps.useCases.appeals.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/appeals/{appealPathId}
 * Operation: updateAppealPath
 */
export async function updateAppealPath(
  request: FastifyRequest<{ Params: { appealPathId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AppealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateAppealPathInput = {
    appealPathId: request.params.appealPathId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.appeals.update.execute(input);
  return reply.code(200).send(result);
}


