/**
 * Handlers for UseCase
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { UsecasesDomainModule } from "../dependencies/usecases-ddd.dependencies.js";
import type { CreateUseCaseInput, GetUseCaseInput, ListUseCasesInput, UpdateUseCaseInput } from "@paritya/services/usecases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/use-cases
 * Operation: listUseCases
 */
export async function listUseCases(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], category?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: UsecasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListUseCasesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.useCases.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/use-cases
 * Operation: createUseCase
 */
export async function createUseCase(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: UsecasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateUseCaseInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.useCases.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/use-cases/{useCaseId}
 * Operation: getUseCase
 */
export async function getUseCase(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UsecasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetUseCaseInput = {
    useCaseId: request.params.useCaseId,
  };
  const result = await deps.useCases.useCases.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/use-cases/{useCaseId}
 * Operation: updateUseCase
 */
export async function updateUseCase(
  request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UsecasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateUseCaseInput = {
    useCaseId: request.params.useCaseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.useCases.update.execute(input);
  return reply.code(200).send(result);
}


