/**
 * PlaybookRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlaybookRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PlaybookRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PlaybookRepository,
} from "@paritya/services/playbooks";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PlaybookRepositoryDdb } from "./playbook-repository.ddb.js";

/**
 * PlaybookRepositoryAdapter
 *
 * Implements PlaybookRepository port for infrastructure layer.
 */
export class PlaybookRepositoryAdapter implements PlaybookRepository {
  private readonly ddb: PlaybookRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PlaybookRepositoryDdb(this.dynamoClient);
  }

  async listPlaybooks(input: Parameters<PlaybookRepository['listPlaybooks']>[0]): Promise<Awaited<ReturnType<PlaybookRepository['listPlaybooks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPlaybooks(input);
  }

  async createPlaybook(input: Parameters<PlaybookRepository['createPlaybook']>[0]): Promise<Awaited<ReturnType<PlaybookRepository['createPlaybook']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPlaybook(input);
  }

  async getPlaybook(input: Parameters<PlaybookRepository['getPlaybook']>[0]): Promise<Awaited<ReturnType<PlaybookRepository['getPlaybook']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPlaybook(input);
  }
}
