/**
 * Appeals DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Appeals Domain Module - Composition root
 *
 * DDD: Composition root for appeals domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AppealRepositoryAdapter,
} from "@paritya/adapters/appeals";
import { getIdGeneratorService } from "@paritya/adapters";
import type { AdapterDynamoDBClient } from "@paritya/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAppealPath,
  ExecuteGetAppealPath,
  ExecuteListAppealPaths,
  ExecuteUpdateAppealPath,
} from "@paritya/services/appeals/usecases";
// Ports (interfaces)
import type {
  AppealRepository,
} from "@paritya/services/appeals/ports";

export interface AppealsDomainModule {
  repos: {
    appeals: AppealRepository;
  };
  useCases: {
    appeals: {
      create: ExecuteCreateAppealPath;
      get: ExecuteGetAppealPath;
      list: ExecuteListAppealPaths;
      update: ExecuteUpdateAppealPath;
    };
  };
}

export function buildAppealsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AppealsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      appeals?: AppealRepository;
    } = {};

    obj.appeals = new AppealRepositoryAdapter(dynamoClient);
    return {
      appeals: obj.appeals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    appeals: {
      create: new ExecuteCreateAppealPath(executionContext, idGenerator, repos.appeals),
      get: new ExecuteGetAppealPath(executionContext, idGenerator, repos.appeals),
      list: new ExecuteListAppealPaths(executionContext, idGenerator, repos.appeals),
      update: new ExecuteUpdateAppealPath(executionContext, idGenerator, repos.appeals),
    },
  };
  return { repos, useCases: useCases as AppealsDomainModule["useCases"] };
}
