/**
 * AppealRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AppealRepository Port
 *
 * DDD: Application port for appealrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAppealPathInput, CreateAppealPathOutput, GetAppealPathInput, GetAppealPathOutput, ListAppealPathsInput, ListAppealPathsOutput, UpdateAppealPathInput, UpdateAppealPathOutput } from "../dto/appeal.dto";
export interface AppealRepository {
  listAppealPaths(input: ListAppealPathsInput): Promise<ListAppealPathsOutput>;
  createAppealPath(input: CreateAppealPathInput): Promise<CreateAppealPathOutput>;
  getAppealPath(input: GetAppealPathInput): Promise<GetAppealPathOutput>;
  updateAppealPath(input: UpdateAppealPathInput): Promise<UpdateAppealPathOutput>;
}

export type { CreateAppealPathInput, CreateAppealPathOutput, GetAppealPathInput, GetAppealPathOutput, ListAppealPathsInput, ListAppealPathsOutput, UpdateAppealPathInput, UpdateAppealPathOutput } from "../dto/appeal.dto";
