/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@paritya/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@paritya/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@paritya/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _appeals from "./appeals/index.js";
import * as _cases from "./cases/index.js";
import * as _dossiers from "./dossiers/index.js";
import * as _evidence from "./evidence/index.js";
import * as _gates from "./gates/index.js";
import * as _identity from "./identity/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _playbooks from "./playbooks/index.js";
import * as _usecases from "./usecases/index.js";

// Export as namespaces
export const appeals = _appeals;
export const cases = _cases;
export const dossiers = _dossiers;
export const evidence = _evidence;
export const gates = _gates;
export const identity = _identity;
export const monitoring = _monitoring;
export const playbooks = _playbooks;
export const usecases = _usecases;
