/**
 * Breach DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Breach DTOs
 *
 * DDD: Application DTOs for Breach use cases.
 */

import type { CreateFairnessBreachRequestInput, ListFairnessBreachesParams } from "@paritya/core/monitoring/types";

export type ListFairnessBreachesInput = ListFairnessBreachesParams;

export type CreateFairnessBreachInput = CreateFairnessBreachRequestInput;

export type ListFairnessBreachesOutput = {};

export type CreateFairnessBreachOutput = {};
