/**
 * Dossiers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dossiers Domain Module - Composition root
 *
 * DDD: Composition root for dossiers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ChecklistItemRepositoryAdapter,
  DossierRepositoryAdapter,
  LanguageTestRepositoryAdapter,
} from "@paritya/adapters/dossiers";
import { getIdGeneratorService } from "@paritya/adapters";
import type { AdapterDynamoDBClient } from "@paritya/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDossier,
  ExecuteCreateLanguageTest,
  ExecuteGetDossier,
  ExecuteListDossiers,
  ExecuteSubmitDossier,
  ExecuteUpsertChecklistItem,
} from "@paritya/services/dossiers/usecases";
// Ports (interfaces)
import type {
  ChecklistItemRepository,
  DossierRepository,
  LanguageTestRepository,
} from "@paritya/services/dossiers/ports";

export interface DossiersDomainModule {
  repos: {
    checklistItems: ChecklistItemRepository;
    dossiers: DossierRepository;
    languageTests: LanguageTestRepository;
  };
  useCases: {
    checklistItems: {
      get: ExecuteUpsertChecklistItem;
    };
    dossiers: {
      create: ExecuteSubmitDossier;
      get: ExecuteGetDossier;
      list: ExecuteListDossiers;
    };
    languageTests: {
      create: ExecuteCreateLanguageTest;
    };
  };
}

export function buildDossiersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DossiersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      checklistItems?: ChecklistItemRepository;
      dossiers?: DossierRepository;
      languageTests?: LanguageTestRepository;
    } = {};

    obj.checklistItems = new ChecklistItemRepositoryAdapter(dynamoClient);
    obj.dossiers = new DossierRepositoryAdapter(dynamoClient);
    obj.languageTests = new LanguageTestRepositoryAdapter(dynamoClient);
    return {
      checklistItems: obj.checklistItems!,
      dossiers: obj.dossiers!,
      languageTests: obj.languageTests!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    checklistItems: {
      get: new ExecuteUpsertChecklistItem(executionContext, idGenerator, repos.checklistItems),
    },
    dossiers: {
      create: new ExecuteSubmitDossier(executionContext, idGenerator, repos.dossiers),
      get: new ExecuteGetDossier(executionContext, idGenerator, repos.dossiers),
      list: new ExecuteListDossiers(executionContext, idGenerator, repos.dossiers),
    },
    languageTests: {
      create: new ExecuteCreateLanguageTest(executionContext, idGenerator, repos.languageTests),
    },
  };
  return { repos, useCases: useCases as DossiersDomainModule["useCases"] };
}
