/**
 * GateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GateRepository,
} from "@paritya/services/gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GateRepositoryDdb } from "./gate-repository.ddb.js";

/**
 * GateRepositoryAdapter
 *
 * Implements GateRepository port for infrastructure layer.
 */
export class GateRepositoryAdapter implements GateRepository {
  private readonly ddb: GateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GateRepositoryDdb(this.dynamoClient);
  }

  async listGateDecisions(input: Parameters<GateRepository['listGateDecisions']>[0]): Promise<Awaited<ReturnType<GateRepository['listGateDecisions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGateDecisions(input);
  }

  async createGateDecision(input: Parameters<GateRepository['createGateDecision']>[0]): Promise<Awaited<ReturnType<GateRepository['createGateDecision']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createGateDecision(input);
  }
}
