/**
 * Appeals Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createAppealPath_Body = z
  .object({
    useCaseId: z.string(),
    modelVersion: z.string(),
    slaHours: z.number().int().gte(1),
    explanationTemplate: z.string().optional(),
    overrideChannels: z.array(z.string()).optional(),
    humanOwnerRole: z.string().optional(),
  })
  .passthrough();
const updateAppealPath_Body = z
  .object({
    slaHours: z.number().int().gte(1),
    explanationTemplate: z.string(),
    overrideChannels: z.array(z.string()),
    humanOwnerRole: z.string(),
    status: z.enum(['draft', 'active', 'retired']),
  })
  .partial()
  .passthrough();

export const schemas: any = {
  createAppealPath_Body,
  updateAppealPath_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/appeals',
    alias: 'listAppealPaths',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'useCaseId',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'modelVersion',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^ap_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string(),
                  modelVersion: z.string(),
                  status: z.enum(['draft', 'active', 'retired']),
                  slaHours: z.number().int().gte(1),
                  explanationTemplate: z.string().optional(),
                  overrideChannels: z.array(z.string()).optional(),
                  humanOwnerRole: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/appeals',
    alias: 'createAppealPath',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createAppealPath_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ap_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string(),
            modelVersion: z.string(),
            status: z.enum(['draft', 'active', 'retired']),
            slaHours: z.number().int().gte(1),
            explanationTemplate: z.string().optional(),
            overrideChannels: z.array(z.string()).optional(),
            humanOwnerRole: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/appeals/:appealPathId',
    alias: 'getAppealPath',
    requestFormat: 'json',
    parameters: [
      {
        name: 'appealPathId',
        type: 'Path',
        schema: z.string().regex(/^ap_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ap_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string(),
            modelVersion: z.string(),
            status: z.enum(['draft', 'active', 'retired']),
            slaHours: z.number().int().gte(1),
            explanationTemplate: z.string().optional(),
            overrideChannels: z.array(z.string()).optional(),
            humanOwnerRole: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/appeals/:appealPathId',
    alias: 'updateAppealPath',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateAppealPath_Body,
      },
      {
        name: 'appealPathId',
        type: 'Path',
        schema: z.string().regex(/^ap_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ap_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string(),
            modelVersion: z.string(),
            status: z.enum(['draft', 'active', 'retired']),
            slaHours: z.number().int().gte(1),
            explanationTemplate: z.string().optional(),
            overrideChannels: z.array(z.string()).optional(),
            humanOwnerRole: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
