/**
 * Routes for EvidencePack
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createEvidencePack, getEvidencePack, listEvidencePacks } from "../handlers/evidence-pack.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function evidencePackRoutes(fastify: FastifyInstance) {
  // POST /v1/evidence-packs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence-packs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await createEvidencePack(request, reply, deps);
      });
    }
  );


  // GET /v1/evidence-packs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence-packs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await listEvidencePacks(request, reply, deps);
      });
    }
  );


  // GET /v1/evidence-packs/{evidencePackId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence-packs/:evidencePackId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { evidencePackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await getEvidencePack(request, reply, deps);
      });
    }
  );


}
