/**
 * Gates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Gates Domain Module - Composition root
 *
 * DDD: Composition root for gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExtendRepositoryAdapter,
  GateRepositoryAdapter,
  RevokeRepositoryAdapter,
  SandboxRepositoryAdapter,
} from "@paritya/adapters/gates";
import { getIdGeneratorService } from "@paritya/adapters";
import type { AdapterDynamoDBClient } from "@paritya/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateGateDecision,
  ExecuteExtendSandboxPermit,
  ExecuteGetSandboxPermit,
  ExecuteListGateDecisions,
  ExecuteListSandboxPermits,
  ExecuteRevokeSandboxPermit,
} from "@paritya/services/gates/usecases";
// Ports (interfaces)
import type {
  ExtendRepository,
  GateRepository,
  RevokeRepository,
  SandboxRepository,
} from "@paritya/services/gates/ports";

export interface GatesDomainModule {
  repos: {
    extends: ExtendRepository;
    gates: GateRepository;
    revokes: RevokeRepository;
    sandboxes: SandboxRepository;
  };
  useCases: {
    extends: {
      get: ExecuteExtendSandboxPermit;
    };
    gates: {
      create: ExecuteCreateGateDecision;
      list: ExecuteListGateDecisions;
    };
    revokes: {
      get: ExecuteRevokeSandboxPermit;
    };
    sandboxes: {
      get: ExecuteGetSandboxPermit;
      list: ExecuteListSandboxPermits;
    };
  };
}

export function buildGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      extends?: ExtendRepository;
      gates?: GateRepository;
      revokes?: RevokeRepository;
      sandboxes?: SandboxRepository;
    } = {};

    obj.extends = new ExtendRepositoryAdapter(dynamoClient);
    obj.gates = new GateRepositoryAdapter(dynamoClient);
    obj.revokes = new RevokeRepositoryAdapter(dynamoClient);
    obj.sandboxes = new SandboxRepositoryAdapter(dynamoClient);
    return {
      extends: obj.extends!,
      gates: obj.gates!,
      revokes: obj.revokes!,
      sandboxes: obj.sandboxes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    extends: {
      get: new ExecuteExtendSandboxPermit(executionContext, idGenerator, repos.extends),
    },
    gates: {
      create: new ExecuteCreateGateDecision(executionContext, idGenerator, repos.gates),
      list: new ExecuteListGateDecisions(executionContext, idGenerator, repos.gates),
    },
    revokes: {
      get: new ExecuteRevokeSandboxPermit(executionContext, idGenerator, repos.revokes),
    },
    sandboxes: {
      get: new ExecuteGetSandboxPermit(executionContext, idGenerator, repos.sandboxes),
      list: new ExecuteListSandboxPermits(executionContext, idGenerator, repos.sandboxes),
    },
  };
  return { repos, useCases: useCases as GatesDomainModule["useCases"] };
}
