/**
 * Usecases Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createUseCase_Body = z
  .object({
    category: z.enum(['credit', 'advice', 'fraud', 'collections', 'other']),
    title: z.string().min(1).max(200),
    description: z.string().max(4000).optional(),
    coverageGaps: z
      .array(
        z.enum([
          'gender',
          'language',
          'geography',
          'informal_sector',
          'thin_file',
          'other',
        ])
      )
      .optional(),
  })
  .passthrough();
const updateUseCase_Body = z
  .object({
    title: z.string().min(1).max(200),
    description: z.string().max(4000),
    coverageGaps: z.array(
      z.enum([
        'gender',
        'language',
        'geography',
        'informal_sector',
        'thin_file',
        'other',
      ])
    ),
    status: z.enum([
      'draft',
      'in_review',
      'sandboxed',
      'production',
      'revoked',
    ]),
  })
  .partial()
  .passthrough();

export const schemas: any = {
  createUseCase_Body,
  updateUseCase_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/use-cases',
    alias: 'listUseCases',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['draft', 'in_review', 'sandboxed', 'production', 'revoked'])
          .optional(),
      },
      {
        name: 'category',
        type: 'Query',
        schema: z
          .enum(['credit', 'advice', 'fraud', 'collections', 'other'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^uc_[0-9A-HJKMNP-TV-Z]{26}$/),
                  providerId: z.string(),
                  category: z.enum([
                    'credit',
                    'advice',
                    'fraud',
                    'collections',
                    'other',
                  ]),
                  title: z.string().min(1).max(200),
                  description: z.string().max(4000).optional(),
                  status: z.enum([
                    'draft',
                    'in_review',
                    'sandboxed',
                    'production',
                    'revoked',
                  ]),
                  coverageGaps: z
                    .array(
                      z.enum([
                        'gender',
                        'language',
                        'geography',
                        'informal_sector',
                        'thin_file',
                        'other',
                      ])
                    )
                    .optional(),
                  sandboxExpiresAt: z
                    .string()
                    .datetime({ offset: true })
                    .optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/use-cases',
    alias: 'createUseCase',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createUseCase_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^uc_[0-9A-HJKMNP-TV-Z]{26}$/),
            providerId: z.string(),
            category: z.enum([
              'credit',
              'advice',
              'fraud',
              'collections',
              'other',
            ]),
            title: z.string().min(1).max(200),
            description: z.string().max(4000).optional(),
            status: z.enum([
              'draft',
              'in_review',
              'sandboxed',
              'production',
              'revoked',
            ]),
            coverageGaps: z
              .array(
                z.enum([
                  'gender',
                  'language',
                  'geography',
                  'informal_sector',
                  'thin_file',
                  'other',
                ])
              )
              .optional(),
            sandboxExpiresAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/use-cases/:useCaseId',
    alias: 'getUseCase',
    requestFormat: 'json',
    parameters: [
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^uc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^uc_[0-9A-HJKMNP-TV-Z]{26}$/),
            providerId: z.string(),
            category: z.enum([
              'credit',
              'advice',
              'fraud',
              'collections',
              'other',
            ]),
            title: z.string().min(1).max(200),
            description: z.string().max(4000).optional(),
            status: z.enum([
              'draft',
              'in_review',
              'sandboxed',
              'production',
              'revoked',
            ]),
            coverageGaps: z
              .array(
                z.enum([
                  'gender',
                  'language',
                  'geography',
                  'informal_sector',
                  'thin_file',
                  'other',
                ])
              )
              .optional(),
            sandboxExpiresAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/use-cases/:useCaseId',
    alias: 'updateUseCase',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateUseCase_Body,
      },
      {
        name: 'useCaseId',
        type: 'Path',
        schema: z.string().regex(/^uc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^uc_[0-9A-HJKMNP-TV-Z]{26}$/),
            providerId: z.string(),
            category: z.enum([
              'credit',
              'advice',
              'fraud',
              'collections',
              'other',
            ]),
            title: z.string().min(1).max(200),
            description: z.string().max(4000).optional(),
            status: z.enum([
              'draft',
              'in_review',
              'sandboxed',
              'production',
              'revoked',
            ]),
            coverageGaps: z
              .array(
                z.enum([
                  'gender',
                  'language',
                  'geography',
                  'informal_sector',
                  'thin_file',
                  'other',
                ])
              )
              .optional(),
            sandboxExpiresAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
