/**
 * UseCase DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: usecases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseCase DTOs
 *
 * DDD: Application DTOs for UseCase use cases.
 */

import type { CreateUseCaseRequestInput, GetUseCaseParams, ListUseCasesParams, UpdateUseCaseParams, UpdateUseCaseRequestInput } from "@paritya/core/usecases/types";

export type ListUseCasesInput = ListUseCasesParams;

export type CreateUseCaseInput = CreateUseCaseRequestInput;

export type GetUseCaseInput = GetUseCaseParams;

export type UpdateUseCaseInput = UpdateUseCaseParams & UpdateUseCaseRequestInput;

export type ListUseCasesOutput = {};

export type CreateUseCaseOutput = {};

export type GetUseCaseOutput = {};

export type UpdateUseCaseOutput = {};
