/**
 * CreateAppealPath handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createAppealPath } from "@paritya/api-server/domains/appeals/handlers";
import type { AppealsDDDDependencies } from "@paritya/api-server/domains/appeals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@paritya/tests/shared";
import { APPEALS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateAppealPath", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AppealsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AppealsDDDDependencies>(
      APPEALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateAppealPath, "execute").mockResolvedValue(useCaseResult);

    await createAppealPath(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateAppealPath.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
