/**
 * Repository interface for ChecklistItem
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ChecklistItemEntity
} from "../models/checklist-item.entity.js";
import type {
  ChecklistItem
} from "../types/index.js";
/**
 * ChecklistItemRepository Interface
 */
export interface ChecklistItemRepository extends CreateReadRepository<ChecklistItemEntity, ChecklistItem, string, Record<string, never>> {

}
