/**
 * Routes for Dossier
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDossier, getDossier, listDossiers, submitDossier } from "../handlers/dossier.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dossierRoutes(fastify: FastifyInstance) {
  // POST /v1/dossiers (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/dossiers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDossiersDependenciesForRequest();
        await createDossier(request, reply, deps);
      });
    }
  );


  // GET /v1/dossiers (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/dossiers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDossiersDependenciesForRequest();
        await listDossiers(request, reply, deps);
      });
    }
  );


  // GET /v1/dossiers/{dossierId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/dossiers/:dossierId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dossierId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDossiersDependenciesForRequest();
        await getDossier(request, reply, deps);
      });
    }
  );


  // POST /v1/dossiers/{dossierId} (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/dossiers/:dossierId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dossierId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDossiersDependenciesForRequest();
        await submitDossier(request, reply, deps);
      });
    }
  );


}
