/**
 * Routes for LanguageTest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createLanguageTest } from "../handlers/language-test.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function languageTestRoutes(fastify: FastifyInstance) {
  // POST /v1/dossiers/{dossierId}/language-tests (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/dossiers/:dossierId/language-tests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dossierId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDossiersDependenciesForRequest();
        await createLanguageTest(request, reply, deps);
      });
    }
  );


}
