/**
 * Routes for Appeal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAppealPath, getAppealPath, listAppealPaths, updateAppealPath } from "../handlers/appeal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function appealRoutes(fastify: FastifyInstance) {
  // POST /v1/appeals (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/appeals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAppealsDependenciesForRequest();
        await createAppealPath(request, reply, deps);
      });
    }
  );


  // GET /v1/appeals (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/appeals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAppealsDependenciesForRequest();
        await listAppealPaths(request, reply, deps);
      });
    }
  );


  // GET /v1/appeals/{appealPathId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/appeals/:appealPathId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { appealPathId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAppealsDependenciesForRequest();
        await getAppealPath(request, reply, deps);
      });
    }
  );


  // PATCH /v1/appeals/{appealPathId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/appeals/:appealPathId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { appealPathId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAppealsDependenciesForRequest();
        await updateAppealPath(request, reply, deps);
      });
    }
  );


}
