/**
 * GateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateRepository Port
 *
 * DDD: Application port for gaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateGateDecisionInput, CreateGateDecisionOutput, ListGateDecisionsInput, ListGateDecisionsOutput } from "../dto/gate.dto";
export interface GateRepository {
  listGateDecisions(input: ListGateDecisionsInput): Promise<ListGateDecisionsOutput>;
  createGateDecision(input: CreateGateDecisionInput): Promise<CreateGateDecisionOutput>;
}

export type { CreateGateDecisionInput, CreateGateDecisionOutput, ListGateDecisionsInput, ListGateDecisionsOutput } from "../dto/gate.dto";
