/**
 * RevokeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevokeRepository Port
 *
 * DDD: Application port for revokerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RevokeSandboxPermitInput, RevokeSandboxPermitOutput } from "../dto/revoke.dto";
export interface RevokeRepository {
  revokeSandboxPermit(input: RevokeSandboxPermitInput): Promise<RevokeSandboxPermitOutput>;
}

export type { RevokeSandboxPermitInput, RevokeSandboxPermitOutput } from "../dto/revoke.dto";
