/**
 * SandboxRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SandboxRepository Port
 *
 * DDD: Application port for sandboxrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSandboxPermitInput, GetSandboxPermitOutput, ListSandboxPermitsInput, ListSandboxPermitsOutput } from "../dto/sandbox.dto";
export interface SandboxRepository {
  listSandboxPermits(input: ListSandboxPermitsInput): Promise<ListSandboxPermitsOutput>;
  getSandboxPermit(input: GetSandboxPermitInput): Promise<GetSandboxPermitOutput>;
}

export type { GetSandboxPermitInput, GetSandboxPermitOutput, ListSandboxPermitsInput, ListSandboxPermitsOutput } from "../dto/sandbox.dto";
