/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-dossier.handler.test.js";
export * from "./get-dossier.handler.test.js";
export * from "./list-dossiers.handler.test.js";
export * from "./submit-dossier.handler.test.js";
