/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Evidence Domain Use Cases
 * 
 * List of all use case names for the evidence domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const EVIDENCE_USE_CASES = [
  "executeCreateEvidencePack",
  "executeGetEvidencePack",
  "executeListEvidencePacks"
] as const;
