/**
 * EvidencePack Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/evidence.openapi.types.js";
import { schemas } from "../schemas/evidence.schemas.js";

/**
 * Entity: EvidencePackEntity
 * Description: Represents the EvidencePack domain model.
 * Source: schemas.EvidencePack
 * Type: Domain Entity (API)
 */
export const EvidencePackEntitySchema = schemas.EvidencePack;
export type EvidencePackEntity = components["schemas"]["EvidencePack"];
