/**
 * Handlers for Sandbox
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GatesDomainModule } from "../dependencies/gates-ddd.dependencies.js";
import type { GetSandboxPermitInput, ListSandboxPermitsInput } from "@paritya/services/gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/sandboxes
 * Operation: listSandboxPermits
 */
export async function listSandboxPermits(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSandboxPermitsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.sandboxes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/sandboxes/{sandboxPermitId}
 * Operation: getSandboxPermit
 */
export async function getSandboxPermit(
  request: FastifyRequest<{ Params: { sandboxPermitId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSandboxPermitInput = {
    sandboxPermitId: request.params.sandboxPermitId,
  };
  const result = await deps.useCases.sandboxes.get.execute(input);
  return reply.code(200).send(result);
}


