/**
 * ChecklistItemRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChecklistItemRepository Port
 *
 * DDD: Application port for checklistitemrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { UpsertChecklistItemInput, UpsertChecklistItemOutput } from "../dto/checklist-item.dto";
export interface ChecklistItemRepository {
  upsertChecklistItem(input: UpsertChecklistItemInput): Promise<UpsertChecklistItemOutput>;
}

export type { UpsertChecklistItemInput, UpsertChecklistItemOutput } from "../dto/checklist-item.dto";
