/**
 * DossierRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DossierRepository Port
 *
 * DDD: Application port for dossierrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDossierInput, CreateDossierOutput, GetDossierInput, GetDossierOutput, ListDossiersInput, ListDossiersOutput, SubmitDossierInput, SubmitDossierOutput } from "../dto/dossier.dto";
export interface DossierRepository {
  listDossiers(input: ListDossiersInput): Promise<ListDossiersOutput>;
  createDossier(input: CreateDossierInput): Promise<CreateDossierOutput>;
  getDossier(input: GetDossierInput): Promise<GetDossierOutput>;
  submitDossier(input: SubmitDossierInput): Promise<SubmitDossierOutput>;
}

export type { CreateDossierInput, CreateDossierOutput, GetDossierInput, GetDossierOutput, ListDossiersInput, ListDossiersOutput, SubmitDossierInput, SubmitDossierOutput } from "../dto/dossier.dto";
