/**
 * LanguageTestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LanguageTestRepository Port
 *
 * DDD: Application port for languagetestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateLanguageTestInput, CreateLanguageTestOutput } from "../dto/language-test.dto";
export interface LanguageTestRepository {
  createLanguageTest(input: CreateLanguageTestInput): Promise<CreateLanguageTestOutput>;
}

export type { CreateLanguageTestInput, CreateLanguageTestOutput } from "../dto/language-test.dto";
