/**
 * ListPlaybook DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPlaybooksParams } from "@paritya/core/playbooks";

export function createListPlaybookRequest(overrides: Partial<ListPlaybooksParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
