/**
 * Revoke DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Revoke DTOs
 *
 * DDD: Application DTOs for Revoke use cases.
 */

import type { RevokeSandboxPermitParams } from "@paritya/core/gates/types";

export type RevokeSandboxPermitInput = RevokeSandboxPermitParams;

export type RevokeSandboxPermitOutput = {};
