/**
 * Sandbox DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sandbox DTOs
 *
 * DDD: Application DTOs for Sandbox use cases.
 */

import type { GetSandboxPermitParams, ListSandboxPermitsParams } from "@paritya/core/gates/types";

export type ListSandboxPermitsInput = ListSandboxPermitsParams;

export type GetSandboxPermitInput = GetSandboxPermitParams;

export type ListSandboxPermitsOutput = {};

export type GetSandboxPermitOutput = {};
