/**
 * ExecuteExtendSandboxPermit - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExtendSandboxPermit Use Case
 *
 * DDD: Application use case for get Extend.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExtendSandboxPermitInput, ExtendSandboxPermitOutput } from "../dto/extend.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { ExtendRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteExtendSandboxPermit {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly extend: ExtendRepository
  ) {}

  async execute(input: ExtendSandboxPermitInput): Promise<ExtendSandboxPermitOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: expiresAt, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).sandboxPermitId) {
      throw new ValidationError("sandboxPermitId is required");
    }
    const sandboxpermitId = (input as any).sandboxPermitId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.extend.extendSandboxPermit({ sandboxPermitId: sandboxpermitId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${sandboxpermitId}`);
    }

    return entity as ExtendSandboxPermitOutput;
  }
}
