/**
 * Evidence Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createEvidencePack_Body = z
  .object({
    useCaseId: z.string(),
    includesRawPii: z.boolean().optional().default(false),
    rawPiiAuditReason: z.string().optional(),
    includeCivilSocietySummary: z.boolean().optional().default(true),
  })
  .passthrough();

export const schemas: any = {
  createEvidencePack_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/evidence-packs',
    alias: 'listEvidencePacks',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'useCaseId',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^ep_[0-9A-HJKMNP-TV-Z]{26}$/),
                  useCaseId: z.string(),
                  status: z.enum(['pending', 'ready', 'failed']),
                  includesRawPii: z.boolean(),
                  rawPiiAuditReason: z.string().optional(),
                  downloadUrl: z.string().url().optional(),
                  civilSocietySummary: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  readyAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/evidence-packs',
    alias: 'createEvidencePack',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createEvidencePack_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ep_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string(),
            status: z.enum(['pending', 'ready', 'failed']),
            includesRawPii: z.boolean(),
            rawPiiAuditReason: z.string().optional(),
            downloadUrl: z.string().url().optional(),
            civilSocietySummary: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            readyAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/evidence-packs/:evidencePackId',
    alias: 'getEvidencePack',
    requestFormat: 'json',
    parameters: [
      {
        name: 'evidencePackId',
        type: 'Path',
        schema: z.string().regex(/^ep_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^ep_[0-9A-HJKMNP-TV-Z]{26}$/),
            useCaseId: z.string(),
            status: z.enum(['pending', 'ready', 'failed']),
            includesRawPii: z.boolean(),
            rawPiiAuditReason: z.string().optional(),
            downloadUrl: z.string().url().optional(),
            civilSocietySummary: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            readyAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
