/**
 * ExecuteCreateAppealPath - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAppealPath Use Case
 *
 * DDD: Application use case for create Appeal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAppealPathInput, CreateAppealPathOutput } from "../dto/appeal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@paritya/services/_shared/index.js";
import type { AppealRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAppealPath {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appeal: AppealRepository
  ) {}

  async execute(input: CreateAppealPathInput): Promise<CreateAppealPathOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aplId();

    // All field names extracted from OpenAPI spec: explanationTemplate, humanOwnerRole, modelVersion, overrideChannels, slaHours, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.useCaseId) {
      throw new ValidationError("useCaseId is required");
    }
    if (!input.modelVersion) {
      throw new ValidationError("modelVersion is required");
    }
    if (!input.slaHours) {
      throw new ValidationError("slaHours is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (appeals domain)
    const entityId = this.idGenerator.aplId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.appeal.createAppealPath({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAppealPathOutput;
  }
}
