/**
 * Playbook Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PlaybookEntity } from "@paritya/core/playbooks/models/index.js";
import { playbooksSchemas } from "@paritya/core/playbooks";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "plb";

export function createPlaybook(overrides: Partial<PlaybookEntity> = {}) {
  const raw = {
    id: overrides.id ?? `pb_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    anonymised: overrides.anonymised ?? faker.datatype.boolean(),
    title: overrides.title ?? faker.lorem.sentence(),
    useCaseType: overrides.useCaseType ?? "credit",
    ...overrides,
  };

  return playbooksSchemas.Playbook.parse(raw);
}

export function playbookBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPlaybook(overrides));
}
