/**
 * Appeal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: appeals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Appeal DTOs
 *
 * DDD: Application DTOs for Appeal use cases.
 */

import type { CreateAppealPathRequestInput, GetAppealPathParams, ListAppealPathsParams, UpdateAppealPathParams, UpdateAppealPathRequestInput } from "@paritya/core/appeals/types";

export type ListAppealPathsInput = ListAppealPathsParams;

export type CreateAppealPathInput = CreateAppealPathRequestInput;

export type GetAppealPathInput = GetAppealPathParams;

export type UpdateAppealPathInput = UpdateAppealPathParams & UpdateAppealPathRequestInput;

export type ListAppealPathsOutput = {};

export type CreateAppealPathOutput = {};

export type GetAppealPathOutput = {};

export type UpdateAppealPathOutput = {};
